shadow = false
borders = "simple"

[colors]
background = ""

view = "#000000"
shadow = "#ffffff"
text = "#ffffff"

primary = "#8a771f"
secondary = "#ffffff"
tertiary = "#ffffff"

title_primary = "#8a771f"
title_secondary = "#ffffff"

highlight = "#3e350d"
highlight_inactive = "#e1c02e"
highlight_text = "#5f5115"

# [styles.highlight]
#     effects = []
#     front = "#8a771f"
#     back = "#8a771f"