shadow = false
borders = "simple"

[colors]
background = ""

view = "#000000"
shadow = "#ffffff"
text = "#ffffff"

primary = "#8a771f"
secondary = "#ffffff"
tertiary = "#ffffff"

title_primary = "#8a771f"
title_secondary = "#ffffff"

highlight = "#9f8821"
highlight_inactive = "#4f4412"
highlight_text = "#4f4311"

# [styles.highlight]
#     effects = []
#     front = "#8a771f"
#     back = "#8a771f"